### ISSUE TITLE
PIP install error

### ISSUE THREAD

**Issue by actuarysailor** [manugarg/pacparser#140]
![image](https://user-images.githubusercontent.com/24359398/206819166-48f46e3d-59cb-4fd7-ab60-49677452094e.png)

![image](https://user-images.githubusercontent.com/24359398/206819226-c035808a-94d5-4fda-848b-c2b59c9d23c1.png)

**Comment by Taknok** [comment]
`pip` add new controls while installing a package. The check with the pypa version and metadata version is triggering here as the pypa declared version is 1.4.0 but the metadata version is 1.0.0.

The metadata version is 1.0.0 because the CI never set this env var `PACPARSER_VERSION`. Thus, the line https://github.com/manugarg/pacparser/blob/853e8f45607cb07b877ffd270c63dbcdd5201ad9/src/pymod/setup.py#L75 set the metadata version to 1.0.0.

The CI as to set this env to the release version.

**Comment by manugarg** [comment]
@Taknok If I understand it correctly, what you're suggesting is that since there is a mismatch in package version and binary version, pip is trying to rebuild the module. Is that correct?

**Comment by manugarg** [comment]
Actually I looked at the windows whl file here: https://pypi.org/project/pacparser/1.4.0/#modal-close (Just change extension to .zip to examine the file).

Metadata seems correct.

**Comment by manugarg** [comment]
@actuarysailor There are actually two possible reasons for pip to build it from sources:
* You're using win32 and we don't build and distribute a package for win32.
* You're using Python3.11 and there's no package for that.

If it's the latter, i.e. it's just the Python version mismatch, I've just submitted a change to build module for Python 3.11 as well: #141.

**Comment by manugarg** [comment]
I could both: reproduce the issue, and verify the fix.
