### ISSUE TITLE
array of ip addresses not used

### ISSUE THREAD

**Issue by peterskurt** [manugarg/pacparser#37]
Is there a way to determine if the system is using an array of IP addresses for the host that myIpAddressEx() provides.  It doesn't give the same functionality of the browser because of that.  I had to add my system's list of ip returned by myIpAddressEx in setmyip() to get the same behavior.  Otherwise it seems like it just returns the first IP?

**Comment by DrDaveD** [comment]
According to the [code](https://github.com/pacparser/pacparser/blob/master/src/pacparser.c) (see especially my_ip_ex() and resolve_host()), by default myIpAddressEx() should return a semi-colon separated list of whatever getnameinfo() returns using the host name from gethostname().  That would be multiple IP addresses (in particular IPv4 and IPv6) for a single network interface.  It does not look up all the IP addresses on all network interfaces that a host may have.  This seems to match the [Microsoft definition of this function](https://msdn.microsoft.com/en-us/library/windows/desktop/gg308481%28v=vs.85%29.aspx).  Does a browser behave differently, and if so which one?

In order to handle hosts with multiple interfaces, I believe the solution that I submitted in this [pull request](https://github.com/pacparser/pacparser/pull/36) is better.

**Comment by manugarg** [comment]
@peterskurt it's too late now, but I was closing old tickets and saw this one. I verified that `myIpAddressEx` returns multiple addresses if host has multiple addresses configured through /etc/hosts (on Unix, not sure about windows). Simple way to verify, create a PAC file like this:

```
function FindProxyForURL(url, host) {
  if (
    typeof myIpAddressEx == 'function'
  )
    return myIpAddressEx();
  else return 'Direct';
}
```

I think important point is having multiple addresses on interface is not enough, these addresses should be mapped to the hostname through /etc/hosts. This matches @DrDaveD's description above.
