### ISSUE TITLE
Can parparser be installed by pip install?

### ISSUE THREAD

**Issue by jizusun** [manugarg/pacparser#61]
I'm new to Python, and I find it very easy to use `pip install` to install Python library. 
But when I read through the `INSTALL` file, and I can't find a way to install it as I usually does.

I was wondering if parparser can be installed by pip install?
Thanks.

**Comment by kujiy** [comment]
I need pip install too! Today I published [pacparser-web](https://github.com/kujiy/pacparser-web) and tried to deploy my demo to heroku. But I don't know how to make pacparser inside heroku's system. If I can use pip install for pacparser, my demo will work on heroku. And my docker entrypoint.sh will be more slim also.

I haven't regist any pip but I think this is a doc. I appreciate it if you could regist pacparser to pip.
http://peterdowns.com/posts/first-time-with-pypi.html

Thank you.

**Comment by shaleh** [comment]
Sadly this will be difficult.

To make `pip install` work you need to have a `pacparser` library installed on your system already. There currently is not one made by the C half of this repo. So that is step one. Make a proper C library out of `pacparser.c`.

Step 2 is splitting the Python module out into its own repo. Then `pip` could easily install it. But you would always need to install the `pacparser` C library before `pip` would work.

**Comment by shaleh** [comment]
Slight mispeaking on my part.

There is a pacparser lib. The lack of the internal libjs may be an issue.

**Comment by manugarg** [comment]
Now it can be. See:
https://github.com/manugarg/pacparser/commit/6c615e220ee692b61564dd008841f7e9813e56c0
